### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by julj** [torch/ezinstall#38]
Hi,

I'm trying to install Torch on Ubuntu 14.04.

When running

`curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-all | bash`

I get permission issues, eg.

```
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/include/luaconf.h
CMake Error at luajit-2.0/cmake_install.cmake:36 (FILE):
  file INSTALL cannot set permissions on "/usr/local/include/luaconf.h"
```

if I add sudo, the command does not even seem to run:

`sudo curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-all | bash`

What's wrong?

**Comment by soumith** [comment]
Hey Julien, please follow the instructions on our website! http://torch.ch

**Comment by julj** [comment]
Ok, thanks, it works flawlessly .
There is still an issue with the `https://raw.githubusercontent.com/torch/ezinstall/master/install-all` script though!
