### ISSUE TITLE
OpenBLAS could not be compiled

### ISSUE THREAD

**Issue by mixxen** [torch/ezinstall#39]
Error running ezinstall on Ubuntu 14.04:

Cloning into 'OpenBLAS'...
Makefile.system:370: *** OpenBLAS: Cannot set both USE_OPENMP=1 and USE_THREAD=0. The USE_THREAD=0 is only for building single thread version..  Stop.
Error. OpenBLAS could not be compiled

Seems to be related to this commit:

https://github.com/xianyi/OpenBLAS/commit/771b18ae9c3aa70f4a2497b59700e06819a6ae30

**Comment by laotao** [comment]
Ran into the same issue. Did you solve it?

**Comment by mobiledevver** [comment]
+1

**Comment by mixxen** [comment]
Here is what I did to make it install:

https://github.com/mixxen/ezinstall/commit/16ae9fdb32279249fd0fdb9c0f8e48947c52162b

Seems to be an issue on systems with only one core available...like a small cloud compute node.

**Comment by mobiledevver** [comment]
That worked.  Thx!

**Comment by soumith** [comment]
Thanks @mixxen, fixed in trunk via commit: https://github.com/torch/ezinstall/commit/cbee09e71d2ce77271bfcd4429cbd36cd82de32c

**Comment by hedes1992** [comment]
And I met the similar question, I read the installTorch.sh, and find that "libgfortran-dev" not "apt-get install" in the ubuntu. So I just install the libgfortran-4.6-dev, whose version is matched with my gcc version.

**Comment by power0341** [comment]
same issue here, since the script has been already updated for single core machine, the problem caused by missing other deps, such as "libgfortran". So, simply type `sudo apt-get install libgfortran-4.7-dev`  and it solves my problem.

**Comment by wangg12** [comment]
solved by `sudo apt-get install libgfortran-4.8-dev`

**Comment by zhongczlb** [comment]
solved by sudo apt-get install libgfortran-4.8-dev

**Comment by nullbyte91** [comment]
Solved by sudo apt-get install libopenblas-dev

**Comment by leeivan** [comment]
Solved by sudo apt-get install libopenblas-dev
