### ISSUE TITLE
Add a warning for Archlinux users

### ISSUE THREAD

**Issue by mpiffault** [torch/ezinstall#49]
An Archlinux user attempting to install dependencies via the install-deps script without an up-to-date package lists is likely going into errors when pacman will try to fetch the required packages (as I did).
This is because Arch is a rolling release, and the package lists are permanently updated.

As stated [here](https://wiki.archlinux.org/index.php/Pacman#Installing_packages) , it is strongly discouraged to refresh the package list without updating the system (because dependencies conflicts would certainly result of it).
And naturally it would be a really bad thing to update the system of the user without it's permission.

All those to say it would be good to add a warning message on the archlinux part, telling the user to update it's system prior to let the script do it's job.

**Comment by soumith** [comment]
thanks for the feedback. Another arch user added the support to the install-deps script (most of us dont use arch). If you can send in a patch to fix that in a more reasonable way, i'd be happy to accept it.

**Comment by mpiffault** [comment]
Done !
See https://github.com/torch/ezinstall/pull/50
It's not a perfect solution, but it's better than nothing I think.

**Comment by soumith** [comment]
Thanks a lot martin!
