### ISSUE TITLE
is ipython a requirement?

### ISSUE THREAD

**Issue by kylemcdonald** [torch/ezinstall#52]
After running this script a few times recently on fresh machines, I get:

```
bash: line 216: ipython: command not found
WARNING: Your ipython version is too old.  Type "ipython --version" to see this.  Should be at least version 2
```

Then I go back, and run:

```
sudo easy_install pip
sudo pip install ipython
```

and re-run the `install-deps`. But it's unclear if iPython is necessary, or only if it needs to be up to date if I want to use it with Torch.

**Comment by soumith** [comment]
it is only necessary to use iTorch.

**Comment by xyxxyx** [comment]
@soumith , Hi, smouith. I have a similar problem when I install torch. 

First, I install the torch as the the official instruction , 'bash install-deps'. However, the terminal shows 'Cannot add PPA: 'ppa:jtaylor/ipython'.' 

Then I try to install ipython using the source code and this time the terminal shows 'WARNING: Your ipython version is too old.  Type "ipython --version" to see this.  Should be at least version 2 '  

 I want to continue to install the torch with 'sh ./install.sh', it shows 
./install.sh: 34: ./install.sh: [[: not found
./install.sh: 40: ./install.sh: [[: not found
fatal: Not a git repository (or any parent up to mount point /data1)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

For solving the problem , I try to enter 'pip show ipython' , it shows

Metadata-Version: 1.1
Name: ipython
Version: 4.2.0
Summary: IPython: Productive Interactive Computing
Home-page: http://ipython.org
Author: The IPython Development Team
Author-email: ipython-dev@scipy.org
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires:
Classifiers:
  Framework :: IPython
  Intended Audience :: Developers
  Intended Audience :: Science/Research
  License :: OSI Approved :: BSD License
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Topic :: System :: Shells

The version of ipython is more than 2. Can you give me a help? Thank you.
