### ISSUE TITLE
Ubuntu 12.04 not supported?

### ISSUE THREAD

**Issue by lukeyeager** [torch/ezinstall#54]
https://travis-ci.org/lukeyeager/DIGITS/builds/67444424

> ==> Only Ubuntu, Fedora, Archlinux and CentOS distributions are supported.

I think #51 broke my TravisCI script. Now the `install-deps` script thinks Ubuntu 12.04 isn't supported.

**Comment by soumith** [comment]
I've reverted #51 immediately for now. Will merge when I review it more carefully.

**Comment by lukeyeager** [comment]
> I've reverted #51 immediately for now. 

Thanks!

**Comment by mcsaucy** [comment]
Hey @lukeyeager, I'm a little confused. I just tested #51 against 12.04 and it has completed without issue. Also, looking at the log for the Travis build you linked, I'm seeing "==> Torch7's dependencies have been installed" at line 17204, but no traces of "==> Only Ubuntu, Fedora, Archlinux and CentOS distributions are supported."

Do you have any other information that could help me reproduce and correct this issue?

**Comment by lukeyeager** [comment]
@mcsaucy Sorry, I retriggered that build once Soumith reverted the script. I don't think you can recover the original log :cry:  But as I recall, there wasn't any other helpful information in there other than what I posted.
