### ISSUE TITLE
torch does not have Tensor field

### ISSUE THREAD

**Issue by ShijianTang** [torch/ezinstall#71]
Hi,

I am trying to install torch on Mac OS X 10.10.

I run the script and it seems installed successfully.

.....
packages installed:
    - sundown   :  ok
    - cwrap     :  ok
    - paths     :  ok
    - torch     :  ok
    - nn        :  ok
    - dok       :  ok
    - gnuplot   :  ok
    - qtlua     :  ok
    - qttorch   :  ok
    - lfs       :  ok
    - penlight  :  ok
    - sys       :  ok
    - xlua      :  ok
    - image     :  ok
    - optim     :  ok
    - cjson     :  ok
    - trepl     :  ok

INFO: Torch installed successfully.
.....

But when I try to type torch.Tensor, it has the error:

<img width="594" alt="screen shot 2015-09-16 at 6 40 33 pm" src="https://cloud.githubusercontent.com/assets/11225386/9922867/7a806d2a-5ca2-11e5-9f33-20cd2aad7ff4.png">

Could you please help me to figure out what is wrong?

Thanks!!!

**Comment by soumith** [comment]
we dont actually support this install method anymore. I suggest that you first run this script:
https://github.com/torch/ezinstall/blob/master/clean-old.sh

to clean your install, and then use the commands on our website:
http://torch.ch/docs/getting-started.html#_
