### ISSUE TITLE
bash: line 2: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by lukeyeager** [torch/ezinstall#80]
We're currently using the `install-deps` script for [DIGITS](https://github.com/NVIDIA/DIGITS) TravisCI builds. It's started failing on me in the last two days with errors like this (but only intermittently?):
```
$ travis_wait ./scripts/travis/install-torch-wrapper.sh $(pwd)/deps/torch $(pwd)/torch-install-log.txt
Still running (1 of 20): ./scripts/travis/install-torch-wrapper.sh /home/travis/build/lukeyeager/DIGITS/deps/torch /home/travis/build/lukeyeager/DIGITS/torch-install-log.txt
The command ./scripts/travis/install-torch-wrapper.sh /home/travis/build/lukeyeager/DIGITS/deps/torch /home/travis/build/lukeyeager/DIGITS/torch-install-log.txt exited with 1.
Log:
+++'[' 2 -ne 2 ']'
+++INSTALL_DIR=/home/travis/build/lukeyeager/DIGITS/deps/torch
+++LOG_FILE=/home/travis/build/lukeyeager/DIGITS/torch-install-log.txt
+++./scripts/travis/install-torch.sh /home/travis/build/lukeyeager/DIGITS/deps/torch
+++cat /home/travis/build/lukeyeager/DIGITS/torch-install-log.txt
++++'[' 1 -ne 1 ']'
++++INSTALL_DIR=/home/travis/build/lukeyeager/DIGITS/deps/torch
++++mkdir -p /home/travis/build/lukeyeager/DIGITS/deps/torch
++++bash
++++curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps
bash: line 2: syntax error near unexpected token `newline'
bash: line 2: `<?xml version="1.0" encoding="utf-8"?>'
+++false
/home/travis/build.sh: line 112:  5605 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait ./scripts/travis/install-torch-wrapper.sh $(pwd)/deps/torch $(pwd)/torch-install-log.txt" failed and exited with 1 during .
Your build has been stopped.
```
https://travis-ci.org/lukeyeager/DIGITS/builds/100877937

Can we fix this, or do I need to figure out how to use a different Torch install mechanism? The README says the repo is deprecated, but according to this comment the `install-deps` script should still work:

> The install-deps script is still in use, but the rest of the repo is indeed deprecated.
https://github.com/torch/ezinstall/issues/79#issuecomment-168567912

This could possibly be an issue on my end, totally unrelated to you. I'm looking into it...

**Comment by soumith** [comment]
luke, travis builds are famous for flaky network. It's possible that the install-deps script has been partially downloading occasionally. i've noticed the same in some of my contbuilds.

**Comment by soumith** [comment]
also, have you guys moved to the new travis cluster: https://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by lukeyeager** [comment]
Thanks for the quick response. I'll just keep restarting builds and hope that things settle down.

Are you talking about moving to `trusty`? I'd like to, but we depend on BVLC's Travis scripts to install Caffe on Travis and they're not very motivated to switch over from `precise` - https://github.com/BVLC/caffe/pull/3407. Plus, I've tried it for Caffe and it's been pretty painful so far.

Have you moved to `trusty` with Torch? Or are you just talking about using their container/GCE architectures?

**Comment by soumith** [comment]
I'm talking about their container architectures. I've kept whatever is their default ubuntu install, didn't explicitly move to trusty

**Comment by lukeyeager** [comment]
From what I've read, you need to turn off `sudo` to move to the docker-based container architecture (which we can't do), but you get upgraded to GCE automatically if you don't do anything - https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future.

**Comment by soumith** [comment]
yea all it takes is to remove all sudo calls. The container architecture is soo nice, the builds are way faster and way less flakier.
