### ISSUE TITLE
Problem installing torch on OS X

### ISSUE THREAD

**Issue by snailrowen** [torch/ezinstall#87]
I'm trying to install torch on my OS X el capitan computer, following the official guide(http://torch.ch/docs/getting-started.html). However when I run the commande "source ~/.profile" I simply get "-bash: /Users/johanbjorck/.profile: No such file or directory". I'm pretty new to torch, what should I do?

**Comment by soumith** [comment]
Try:

source ~/torch/install/bin/torch-activate

**Comment by snailrowen** [comment]
I tried doing that, and torch started working. However this does not seem
to be a permanent fix, everytime I start the terminal I have to use this
script to get torch to work. Is there another way to solve this issue?

2016-02-08 20:43 GMT-05:00 Soumith Chintala <notifications@github.com>:

**Comment by soumith** [comment]
if you have ~/.bashrc , then add the line "source ~/torch/install/bin/torch-activate" to ~/.bashrc

**Comment by snailrowen** [comment]
How do I add lines to “~/.bashrc”? Sorry, I’m new to these kind of
installations :(

2016-02-08 20:50 GMT-05:00 Soumith Chintala <notifications@github.com>:

**Comment by soumith** [comment]
you open that file in some kind of text editor and you type the line in.

**Comment by snailrowen** [comment]
Seems like I don’t even have bashrc in my start folder. Can I edit
bash_profile instead?

2016-02-08 20:58 GMT-05:00 Soumith Chintala <notifications@github.com>:

**Comment by soumith** [comment]
sure yea ~/.bash_profile will also work

**Comment by snailrowen** [comment]
Ooh it’s working, thanks a ton :)

2016-02-08 21:01 GMT-05:00 Soumith Chintala <notifications@github.com>:
