### ISSUE TITLE
Does not install on Ubuntu versions newer than trusty?

### ISSUE THREAD

**Issue by romanseidl** [torch/ezinstall#88]
When installing on ubuntu it adds a PPA for ipython:

    deb http://ppa.launchpad.net/jtaylor/ipython/ubuntu wily main
    # deb-src http://ppa.launchpad.net/jtaylor/ipython/ubuntu wily main

The PPA supports *TRUSTY* as the latest version:

http://ppa.launchpad.net/jtaylor/ipython/ubuntu/dists/

As I don't live two years in the past I don't really know what to do about that.

**Comment by soumith** [comment]
> As I don't live two years in the past I don't really know what to do about that.

Thanks for that. We are pretty much community maintained, so any patch to fix it or help with that is appreciated.

**Comment by lukeyeager** [comment]
Looks to me like the standard ipython package should be new enough on Ubuntu >= 14.04. jtaylor's PPA provides v2.3.0 on `trusty` ([here](http://ppa.launchpad.net/jtaylor/ipython/ubuntu/dists/trusty/main/binary-amd64/Packages)), which is the same version provided for `vivid` and `wily` in the standard package ([here](http://packages.ubuntu.com/vivid/ipython)).

**Comment by romanseidl** [comment]
So commenting out the request for the ppa should be sufficient?

I can try that later. Up until now I have switched to a Docker Version.

**Comment by cb** [comment]
#90
