### ISSUE TITLE
Error in install-deps script

### ISSUE THREAD

**Issue by iftekharanam** [torch/ezinstall#92]
Line 95 of the ezinstall/install-deps uses "VERS" instead of VERSION, which causes the CentOS version to fail. I am trying to install torch on an HPC cluster running CentOS 6.6. Since I don't have sudo privilege, I tried to install it inside my directory changing the version. ${centos_major_version} was empty and the version check was failing.

**Comment by soumith** [comment]
fixed now in torch/distro
