### ISSUE TITLE
-bash: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by knowledgeco** [torch/ezinstall#93]
First issue to post on GitHub:

finished installing torch and neural-style on OSX 10.11.13 with some hangups I worked out.

neural-style test functions:

https://github.com/jcjohnson/neural-style/blob/master/INSTALL.md

when I attempt to use the command it fails:

th neural_style.lua -style_image <image.jpg> -content_image <image.jpg>

with this error:

-bash: syntax error near unexpected token `newline'

What to do?

**Comment by soumith** [comment]
can you type the command in, instead of pasting it into bash? there seems to be some terminal issue for your bash and the copy-paste.

**Comment by knowledgeco** [comment]
close issue.  syntax error..  taking the command brackets too seriously.  removing < > < > gives new error I figured out.

Serious n00b!  :)
