### ISSUE TITLE
no CUDA-capable device is detected

### ISSUE THREAD

**Issue by mrtortong** [torch/ezinstall#96]
็็Hi.

Please recommend.

root@tong:/desired/absolute/path/to/deepmask/pretrained/sharpmask# cd $DEEPMASK
root@tong:/desired/absolute/path/to/deepmask# th computeProposals.lua $DEEPMASK/pretrained/deepmask # run DeepMask
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-3624/cutorch/lib/THC/THCGeneral.c line=20 error=38 : no CUDA-capable device is detected
/usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:384: cuda runtime error (38) : no CUDA-capable device is detected at /tmp/luarocks_cutorch-scm-1-3624/cutorch/lib/THC/THCGeneral.c:20
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/trepl/init.lua:384: in function 'require'
	computeProposals.lua:11: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406260

Thank in advance.
mrtortong.

**Comment by albanD** [comment]
`no CUDA-capable device is detected`  do you have a CUDA GPU on your machine?

**Comment by mrtortong** [comment]
Hi albanD
Please recommend.
my notebook is http://specsnotebook.blogspot.com/2011/03/laptop-asus-a42j.html
Video Type
ATI Mobility Radeon HD 5470 1GB

it can use

CUDA-capable GPU
A supported version of Linux with a gcc compiler and toolchain
NVIDIA CUDA Toolkit (available at http://developer.nvidia.com/cuda-downloads)

Or not.

Thank you.
mrtortong

**Comment by albanD** [comment]
You GPU is an ATI one. Thus does not support Nvidia's CUDA.
Unfortunately all main torch GPU packages are based on CUDA.

If you need GPU acceleration for your own project, you should look into [cltorch](https://github.com/hughperkins/cltorch) that is based on OpenCL and thus should work on your GPU.

**Comment by mrtortong** [comment]
albanD
 
               Thank you very much.If i have any question.please recommend me.
I am fresh developer

mrtortong

**Comment by albanD** [comment]
No problem.
Also next time please open a SINGLE issue, don't open one in every single repo. It is quite annoying.
Or even better, use the mailing list here https://groups.google.com/forum/#!forum/torch7
